---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodata-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nodata-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nodata-exporter
    spec:
      containers:
      - image: zhangrongjie/nodata_exporter:1.0
        name: nodata-exporter
        ports:
        - containerPort: 9198
          name: metrics
          protocol: TCP
        args:
        - -u='http://localhost:9090/'
        - -q='up{job="prometheus"}'
        - -r='job,instance'
        readinessProbe:
          tcpSocket:
            port: 9198
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 9198
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: nodata-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: nodata-exporter
spec:
  ports:
  - name: metrics
    port: 9198
    targetPort: metrics
  selector:
    app.kubernetes.io/name: nodata-exporter
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nodata-exporter
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
    - monitoring
  endpoints:
  - interval: 60s
    port: metrics
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app.kubernetes.io/name: nodata-exporter